### ISSUE TITLE
lineage-19.1:  pure gps is not working - tested on GPS Status & GPSTest

### ISSUE THREAD

**Issue by zitronenmelissa** [SwapnilVicky/device_xiaomi_miatoll#1]
I tested gps with lineage-18 & lineage-20 (your builds) and it worked perfectly, but not in lineage-19
GPSTest & GPS Status stuck at "searching gps position"
tested on lineage-19.1-20240122-UNOFFICIAL-miatoll

[logcat.txt](https://github.com/SwapnilVicky/device_xiaomi_miatoll/files/14510009/logcat.txt)

**Comment by SwapnilVicky** [comment]
thanks for reporting the issue with logs, will try to fix it soon. Right now im trying to come up with Lineage-21

**Comment by zitronenmelissa** [comment]
Solved in latest build: 
lineage-19.1-20240318-UNOFFICIAL-miatoll
Thank You
